### PR TITLE
Localizing earnings page

### PR DESCRIPTION
**Pull request by zGerden**

### CODE REVIEW

**Comment by surjithctly** [comment]
Zan,
The Total value of your item sales: is not converting, Its just ₹ NaN 

Also try clicking on the other tabs like 2014, all time, somewhere its $ and some where converted. and something Nan,
Also when clicking referral the graph is not updating.. 

And there is a warning in console : synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check http://xhr.spec.whatwg.org/.

**Comment by zGerden** [comment]
Hello, I have fixed synchronous AJAX request, but I didn't find any currency where Total value of item sales would be N/A?

**Comment by surjithctly** [comment]
Like, the third black box (Total Sales Amount)

And sometimes on the Total of the list below. It will appear when we click some tabs like 2014 / feb etc.. Each time the page is not loading, Instead only that particular div is reloading, that might be the issue.

**Comment by zGerden** [comment]
Well, in which currency you checked, because I also fixed an issue when on any label click values are updated.

**Comment by surjithctly** [comment]
I tried with INR

Regards,
Surjith SM

**Comment by zGerden** [comment]
Okay, I fixed it...

**Comment by surjithctly** [comment]
And, did you see any issue while navigating through years and months?

Also, when clicking referral, the graph is not changing.

**Comment by zGerden** [comment]
I didn't notice any problems, and everything is just as it has to be.

**Comment by surjithctly** [comment]
okay, Let me see once again..

And, Thank you for your contributions. I really appreciate that :)

**Comment by surjithctly** [comment]
Everything is perfect now, except the table for referrals. Because eq(2) should work only for sales, but for refferals, its eq(4) & eq(5)

Anyway I have added this myself. Take the latest and check whether you have any better idea to place this.

Merging this now

**Pull request merged**
